---
- name: Clean up AWX
  hosts: localhost
  connection: local

  tasks:
    - name: Remove Demo Template
      awx.awx.job_template:
        name: Demo Job Template
        organization: Default
        state: absent

    - name: Remove Demo credential
      awx.awx.credential:
        name: Demo Credential
        credential_type: Machine
        state: absent

    - name: Remove Demo inventory
      awx.awx.inventory:
        name: Demo Inventory
        organization: Default
        state: absent

    - name: Remove Demo project
      awx.awx.project:
        name: Demo Project
        organization: Default
        state: absent
