---
- name: Lookup
  hosts: linuxservers

  vars:
    environment2: "{{ lookup('file', 'file.txt') }}"

  tasks:
    - name: Debug Write File Content
      ansible.builtin.debug:
        msg: "{{ environment2 }}"
