---
- name: Vars
  hosts: linuxservers
  become: true

  vars:
    package:
      - httpd
      - mariadb-server
      - php
      - php-mysqlnd

  tasks:
    - name: Install Packages
      ansible.builtin.package:
        name: "{{ package }}"
        state: present

    - name: Enable httpd service
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: true
      register: httpd_status

    - name: Show Status
      ansible.builtin.debug:
        var: httpd_status
