---
- name: Ansible Vault
  hosts: windowsservers
  vars_files:
    - ~/secret.yml
  vars:
    ansible_password: "{{ windows_password }}"
  tasks:
    - name: Install IIS (Web-Server only)
      ansible.windows.win_feature:
        name: Web-Server
        state: present
