---
- name: Azure Webserver
  hosts: localhost
  connection: local
  vars:
    user: alex
    location: northeurope
    virtual_network_name: "webserver_{{ user }}"
    subnet: Webserver
    resource_group: "webserver_{{ user }}"
    domain_sub: "domain{{ user }}"
    ssh_public_key: "{{lookup('file', '~/.ssh/id_rsa.pub') }}"

  tasks:
    - name: Create a virtual network
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: "{{ virtual_network_name }}"
        address_prefixes_cidr: "10.99.0.0/16"
        tags:
            solution: "webserver_{{ user }}"
            delete: ansibletraining

    - name: Create a subnet
      azure.azcollection.azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        virtual_network_name: "{{ virtual_network_name }}"
        name: "{{ subnet }}"
        address_prefix_cidr: "10.99.0.0/24"
